### ISSUE TITLE
Feedback Repository 

### ISSUE THREAD

**Issue by StefanGerrits2** [EyobDejene/frontend-data#10]
## Algemeen
* Goed dat je al een live link hebt.
* Description even updaten en daar ook je live link in stoppen

## Readme
Readme ziet er al goed uit, denk nog even aan het volgende:
* Toekomstige update pattern in readme

 Verder ziet je readme er top uit.

## Wiki
Geen wiki?

**Comment by EyobDejene** [comment]
Thanks!
Mijn wiki was nog niet geüpload, nieuwste versie zit er nu in.
