### ISSUE TITLE
Feedback Concept

### ISSUE THREAD

**Issue by StefanGerrits2** [EyobDejene/frontend-data#11]
* Geef je legenda's nog even een titel.
* Daarnaast vind ik dat de legenda over de cirkelgroottes niet echt meerwaarde geeft op het moment.
* Geen specifieke doelgroep, denk ik?
* Nog geen interactie, voeg dit zeker nog toe.

**Comment by EyobDejene** [comment]
Ik denk dat de legenda nu wel voor zich spreek omdat ik nu alleen de continenten heb gehouden en de size scale eruit heb gehaald.
Doelgroep heb ik beschreven in mijn readme!
Interactie zit er nu in: https://eyobdejene.github.io/frontend-data/
