### ISSUE TITLE
Visualisatie ziet er goed uit!

### ISSUE THREAD

**Issue by emmaoudmaijer** [EyobDejene/frontend-data#6]
Tops:
- Doelgroep wordt goed beschreven
- Concept is duidelijk beschreven
- De animatie aan het begin ziet er leuk uit!

Tips: 
- Misschien een optie om de continenten te groeperen zodat niet alles door elkaar staat
- De kleinste bolletjes kan ik nu niet lezen (misschien kan je nog toevoegen dat je kan inzoomen)
- Nog geen interactie met dat je op een bolletje kan klikken

**Comment by EyobDejene** [comment]
done!
